# Generated by Django 4.0 on 2022-10-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('artists', models.CharField(max_length=200)),
                ('composers', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('album', models.CharField(max_length=100)),
                ('yt_url', models.URLField()),
            ],
        ),
    ]
