# Generated by Django 4.0 on 2022-10-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='song_detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('artists', models.CharField(max_length=200)),
                ('composer', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=4)),
                ('album', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='play_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('songdetail', models.ManyToManyField(blank=True, related_name='songlink', related_query_name='song', to='plydjango.song_detail')),
            ],
        ),
    ]
