# Generated by Django 4.0 on 2022-10-19 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plydjango', '0002_playlist_playlistsongmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='play_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('song', models.ManyToManyField(blank=True, related_name='play', to='plydjango.Song')),
            ],
        ),
        migrations.AlterField(
            model_name='playlistsongmapping',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plydjango.play_list'),
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
