# Generated by Django 4.0 on 2022-10-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plydjango', '0002_alter_play_list_songdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play_list',
            name='songdetail',
            field=models.ManyToManyField(related_name='songs', to='plydjango.song_detail'),
        ),
    ]
